# 8. Numpy

Conteúdos a serem abordado no Numpy

1. Arrays
2. Manipulação de arrays
3. Criação de arrays
4. Métodos matemáticos
5. Índices e fatias
6. Álgebra linear

## 8.1. O que é Numpy?

Uma biblioteca Python voltada a criação de estruturas de **arrays, vetores** que podem possuem multidimensões

**Características:** É rápida, versátil e pertencente ao ecossistema de ferramentas científicas do Python(Numpy, Scipy, Matplotlib, Ipython, Sympy, pandas)

## 8.2. Para quem se destina

Para profissionais que precisam manipular grandes quantidade de dados.

Profissionais de **exatas** como pesquisadores e alunos.

É uma ferramenta muito útil para cálculo numérico.

## 8.3. O que você aprenderá

Manipulação dos arrays(métodos para criação, fatias, operações)

Métodos matemáticos para arrays(usando arrays como matrizes, vetores, resolução de sistemas lineares, problema de autovalor)



## 8.4. Fundamentos de Numpy


### 8.4.1. O que é Numpy?

Arrays de N-dimensões;

Permite executar operações mais rápidas do que em uma lista

Funções e constantes de cálculo pré-construídas

**Vantagens:** Eficiência e versatilidade em trabalhar com dados

### 8.4.2. Arrays multidimensionais

Permite arquivos em 2D(planilha), 3D(arquivos com planilhas), 4D(arquivos de arquivos com planilhas) ... ND.



In [1]:
lista_1 = list(range(10**7))

In [2]:
from time import time

soma_1 = 0

inicio = time()
for i in lista_1:
    soma_1 += i

fim = time()

tempo_1 = fim - inicio

print(soma_1)
print(tempo_1)

49999995000000
0.5411202907562256


In [3]:
from time import time
import numpy as np

inicio = time()
arr = np.array(lista_1, dtype=float)
soma_2 = arr.sum()

fim = time()

tempo_2 = fim - inicio

print(soma_2)
print(tempo_2)

49999995000000.0
0.29506659507751465


### 8.4.3. Arrays

Enquanto um vetor é uma estrutura unidimensional, uma matriz éé uma estrutura bidimensional e um Array é uma estrutura multidimensional.

Outra característica dos arrays é que todos os elementos do array são do mesmo tipo.

### 8.4.4. Propriedades de arrays


| Propriedade | Retorna  | Descrição |
| :-- | :-- | :-- |
| ndim | int |  número de dimensões (axes) |
| shape |  tupla |  quantidade de dados em cada dimensão |
| size | int | número de elementos |
| dtype| dtype | tipo das variáveis dos elementos |

### 8.4.5. Criando um array

Para criar um array basta declaramos uma variável usando a função array(), repassando como argumentos os valores do array dentro de parênteses.

variavel = np.array([valores])

Os parënteses são usados para definir a dimensionalidade do array.
1. []. Apenas um par de parênteses os valores do array seriam de apenas uma dimensão, o que poderia ser analógo a termos uma linha, ou seja, apenas linhas

vetor = np.array([])

2. [[]]. Dois pares de parênteses seria um array com elementos agrupados no segundo índice, analógo a termos uma linha e diversos elementos nas colunas

vetor = np.array([[]])

3. Podemos estender esse entedimento para criar valores em qualquer índice que quisermos.


### 8.4.5. shape

O método shape mostra a quantidade de elementos em cada dimensão do array.

In [4]:
import numpy as np

a_0 = np.array([1, 1, 1])
a_0.shape
# Array unimensional(um colchete), 3 elementos no índice 1, logo, seria análogo a uma matriz linha.

(3,)

In [5]:
a_1 = np.array([[1, 1, 1]])
a_1.shape

# Array bidimensional(dois colchetes), 3 elementos no índice 2, logo, análogo a uma matriz coluna

(1, 3)

### 8.4.6. size

O método size retorna o número de elementos do array, similar a função len() do python, não importando como os elementos estejam dispostos no array.

In [6]:
a_2 = np.array([[1, 2, 3], [4, 5, 6]])

print(a_2.shape)
print(a_2.size)
print(a_2)

(2, 3)
6
[[1 2 3]
 [4 5 6]]


### 8.4.7. ndim

Caso esteja difícil de visualizar as dimensões de um array, podemos usar o método ndim que retorna a quantidade de dimensões.

In [7]:
print(a_0.ndim)
print(a_1.ndim)

1
2


Caso existe um valor de outro tipo no array, todos os valores são convertidos para que todos os elementos do array possuam o mesmo tipo.

In [8]:
a_3 = np.array([[1, "python", 3.0], [4, 5, 6]])
a_3

array([['1', 'python', '3.0'],
       ['4', '5', '6']], dtype='<U32')

### 8.4.8. dtype

O método dtype é usado para saber o tipo de um array

In [9]:
a_4 = np.arange(40).reshape(2, 2, 2, 5)
a_4.dtype

dtype('int32')

## 8.5. Operações com arrays

### Algumas funcionalidades do Numpy
| Comando | Tipo | Descrição |
| :-- | :-- | :-- |
| sin,cos,exp,sqrt | Função | seno,cosseno,exponencial,raíz quadrada |
| pi,nan,inf | constantes(float) | pi, similar a None, infinito |
| +,-,*,/ | operadores | operações aritimética |
| ARRAY1.dot(ARRAY2) | método | multiplicação matricial |


### 8.5.1. Funções trigonométricas

As funções trigonométricas estão disponíveis para uso, recebendo um valor em radianos.
- sin
- cos
- tan
- tanh, cosh, sinh


In [10]:
np.sin(90)  # Como é em radianos, o valor não será 1

0.8939966636005579

In [11]:
np.sin(np.pi / 2)  # agora usando o valor em radianos temos o valor coerente.

1.0

### 8.5.2. Constante

O numpy consta com alguns valores constantes úteis.
- pi: float numérico que representa a constante
- inf: float numérico para representar o infinito
- nan: equivalente ao None, mas como tipo float

In [12]:
print(np.nan)
print(np.pi)
print(np.inf)

nan
3.141592653589793
inf


### 8.5.3. Operações matemáticas

Diferente do que acontecem na matemática podemos realizar as operações abaixo nos arrays

- **Soma:** podemos somar um valor a um array, coisa que na matemática é impossível, a operação irá somar um valor a todos os valores do array;

- **Subtrção:** da mesma forma, podemos subtrair um valor de um array, subtraindo o escalar de todos os valores do array;

- **Divisão:** podemos dividir todos os elementos do array por um valor;

- **Multiplicação:** podemos multiplicar os elementos do array por um valor, **atenção**, se tentarmos multiplicar dois arrays não estaremos realizando um produto escalar ou produto vetorial, mas uma multiplicação de elementos.

In [13]:
a_1 = np.array([4, 5, 6])
a_1

array([4, 5, 6])

In [14]:
a_1 + 2

array([6, 7, 8])

In [15]:
a_1 - 3

array([1, 2, 3])

In [16]:
a_2 = np.array([3, 2, 1])

In [17]:
a_1 * a_2

array([12, 10,  6])

### 8.5.4. Operações matriciais

Para realizar uma multiplicação matricial usamos o método dot(), repassando como argumento o outro array. Vale reassaltar que operações matriciais é necessário que o número de linhas de um array seja igual ao número de colunas do segundo array.
ARRAY1.dot(ARRAY2)

A ordem do uso das matrizes é Colunas x linhas


In [18]:
n1 = np.array([1, 2, 3])
n2 = np.array([[4, 5, 6]])
print(n1.shape)
print(n2.shape)
print(n2.dot(n1))  # Colunas x linhas

(3,)
(1, 3)
[32]


## 8.6. Funções de criação de arrays

### Algumas funções numpy para criar arrays
Em shape devemos repassar a quantidade de elementos de queremos.

| Função | Descrição |
| :-- | :-- |
| zeros(*shape*) | array preenchido com zeros |
| ones(*shape*) | array preenchido com uns |
| eye(*dimensão*) | matriz identidade |
| arange(*início, fim, passo*) | cria um array unidimensioanl |
| linspace(*início, fim, quantidade*) | cria um array unidimensioanl |
| vstack([*arrays*]) e hstack([*arrays*]) | adiciona elementos de um ou mais arrays |


Métodos para dimensionar os arrays:
 - reshape --> retorna um array com o shape indicado, não alterando permanetemente o array
 - resize --> modifica o shape do array em que está sendo aplicado, modificando permanetemente

In [19]:
a_1 = np.zeros(6)
a_1

array([0., 0., 0., 0., 0., 0.])

In [20]:
a_1 = np.ones(3)
print(a_1)
print(a_1 * 2)

[1. 1. 1.]
[2. 2. 2.]


In [21]:
identidade = np.eye(3)
print(identidade)
print(identidade.ndim)
print(identidade.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2
(3, 3)


In [22]:
a_6 = np.arange(0, 5, 0.5)
a_6

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [23]:
a_7 = np.linspace(0, 10, 12)
a_7

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [24]:
a_8 = np.ones(8)
a_8.reshape(2, 4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
a_8.resize(4, 2)
a_8

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

vstack((*arrays*)) e hstack((*arrays*)) | adiciona elementos de um ou mais arrays, o argumento é uma tupla.

- vstack adiciona na vertical, logo é necessário que os arrays tenha a mesma quantidade de colunas
- hstack adiciona na horizontal, logo é necessário que os arrays tenha a mesma quantidade de linhas


In [26]:
a_9 = np.ones(8)
a_9.resize(2, 4)

a_10 = np.zeros(8)
a_10.resize(2, 4)

In [27]:
a_11 = np.vstack((a_9, a_10))
a_11

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
a_12 = np.hstack((a_9, a_10))
a_12

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

## 8.7. Método copy

| Método | Descrição |
| :-- | :-- |
| .copy() | faz a cópia (deep copy) do array. Cuidado! O sinal de igual não executa essa função |


Nota - a propriedade **base** retorna o array utilizado para criar o array em questão, arrays originais não possuem base, pois foram criados a partir de uma função.

array.base




In [29]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
b = a  # adicionamos o mesmo array em outra variável (ligação)
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [31]:
a[0] = 9
print(a)
print(b)

[9 1 2 3 4 5 6 7]
[9 1 2 3 4 5 6 7]


In [32]:
c = a.copy()

c[0] = -3
c

array([-3,  1,  2,  3,  4,  5,  6,  7])

In [33]:
d = a.reshape(2, 4)
d

array([[9, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
d.base is a  # Usamos o operador is ao invés de ==

True

## 8.8. Métodos matemáticos para arrays

### Alguns métodos matemáticos para arrays



| Método | Descrição |
| :-- | :-- |
| .max() / .min()  | retona os valores máximo e mínimo|
| .argmax() / .argmin() | retorna os índices de valor máximo e mínimo |
| .sum() / .mean() / .std() | soma, média e desvio padrão |
|  .cumsum() | retorna um array com a soma acumulada |


In [35]:
my_array = np.arange(8).reshape(2, 4) ** 2
my_array[0][0] = 11
my_array

array([[11,  1,  4,  9],
       [16, 25, 36, 49]])

In [36]:
# Maior valor do array
my_array.max()

49

In [37]:
# Índice do maior valor
my_array.argmax()

7

In [38]:
# Média
my_array.mean()

18.875

In [39]:
# Desvio padrão
my_array.std()

15.599979967935857

In [40]:
# Soma acumulada
my_array.cumsum()
# [11, 11+1, 12+4, 16+9, 25+16, 41+25, 66+36, 102+49]

array([ 11,  12,  16,  25,  41,  66, 102, 151])

## 8.9. Índices e fatias de arrays (Indexing and slicing)

### Guidelines

https://scipy-lectures.org/intro/numpy/array_object.html#indexing-and-slicing


| Sintaxe | Descrição |
| :-- | :-- |
| [i] | para 1 dimensão funciona como nas listas |
| [:i] | exibe um array que vai do índice 0 até o anterior ao i|
| [i:] | exibe um array que vai do índice posterior ao i até o último índice|
|
[::i] | exibe todos os elementos variando de i em i |
| [::-i] | exibe a sequência de elementos de trás pra frente variando de i em i |
| [a:b:c] | início, fim, step |
| [i,j] | para exibir um elemento de uma matriz |
| [i,a:b] | retorna uma fatia da linha i com elementos das colunas de a até b |
| [n,i,j] | outra dimensão, linha, coluna |


Quando criamos um subarray o numpy pode compartilhar memória entre arrays (como mostrado em aulas anteriores com a propriedade .base). Para descobrir se um array compartilha memória com outro use: **np.may_share_memory(a, c)**



In [41]:
import numpy as np

a = np.arange(10) ** 2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [42]:
a[0]

0

In [43]:
b = np.arange(20).reshape(4, 5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [44]:
b[0]

array([0, 1, 2, 3, 4])

In [45]:
b[
    1,
    1,
]

6

In [46]:
b[1, 2:]

array([7, 8, 9])

In [47]:
b[2:, 3:]

array([[13, 14],
       [18, 19]])

In [48]:
c = np.arange(40).reshape(2, 4, 5)
c
# c[z, x, y]
# c[k, i, j]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [49]:
c[1, 1, 1]

26

In [50]:
d = b[2:, 3:]
d

array([[13, 14],
       [18, 19]])

Assim como nas listas existe **shallow copy**, no numpy também, para isso devemos fazer uma **deep copy** usando o método copy ou usando fatiamento de listas.

In [51]:
d.base is b.base

True

In [52]:
np.may_share_memory(b, d)

True

In [53]:
e = b[2::, 3::]

In [54]:
e = b[2:, 3:].copy()

In [55]:
e is d

False

## 8.7. Operações com vetores e matrizes no Numpy

- https://numpy.org/doc/stable/reference/routines.linalg.html
- https://numpy.org/doc/stable/reference/generated/numpy.cross.html


| Funções | Descrição |
| :-- | :-- |
|.dot(a,b) ou @ | retorna o produto escalar entre os vetores **a** e **b** |
| .cross(a,b) | retorna o produto vetorial entre os vetores **a** e **b** |
| .inner(a,b) e .outer(a,b) | retorna o produto interno e externo entre os vetores **a** e **b** |
| .linalg.norm(a) | retorna a norma do vetor **a** |
| .matmul(a,b) | produto entre as matrizes **a** e **b** |
| .linalg.det(A) | retorna o determinante da matriz **A** |
| .linalg.inv(A) | retorna a matriz inversa de **A** |

In [56]:
import numpy as np

a = np.array([1, 2, 3])
a.ndim

1

In [57]:
a

array([1, 2, 3])

In [58]:
# Produto escalar
np.dot(a, a)

# equivalente a
a @ a

14

In [59]:
# Produto interno
np.inner(a, a)

14

In [60]:
# Produto externo
np.outer(a, a)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [61]:
# Norma de um vetor(intensidade)
np.linalg.norm(a)

3.7416573867739413

In [62]:
# Norma do mesmo vetor
print(np.sqrt(1**2 + 2**2 + 3**2))

3.7416573867739413


In [63]:
# Produto vetorial
v_1 = np.array([1, 0, 0])  # vetor i
v_2 = np.array([0, 1, 0])  # vetor j

np.cross(v_1, v_2)

array([0, 0, 1])

#### Matrizes

In [64]:
A = np.array([[1, 2], [4, 4]])
A

array([[1, 2],
       [4, 4]])

In [65]:
np.matmul(A, A)
# Cuidado! isso é diferente de A*A, pois eleva a matriz ao quadrado

# Também podemos simplificar a multiplicação usando
A * A

array([[ 1,  4],
       [16, 16]])

In [66]:
np.linalg.det(A)

-4.0

In [67]:
np.linalg.inv(A)

array([[-1.  ,  0.5 ],
       [ 1.  , -0.25]])

### Vetores com o Sympy

In [68]:
import sympy as sp

In [69]:
a_s = sp.Matrix([1, 2, 3])

In [70]:
a_s

Matrix([
[1],
[2],
[3]])

In [71]:
# Produto escalar
a_s.T * a_s

Matrix([[14]])

In [72]:
# Produto vetorial
a_s * a_s.T

Matrix([
[1, 2, 3],
[2, 4, 6],
[3, 6, 9]])

#### Matrizes

In [73]:
A_s = sp.Matrix([[1, 2], [4, 4]])
A_s * A_s

Matrix([
[ 9, 10],
[20, 24]])

In [74]:
A_s.det()

-4

In [75]:
A_s ** (-1)

Matrix([
[-1,  1/2],
[ 1, -1/4]])

## 8.8. Autovalor e autovetor

- https://numpy.org/doc/stable/reference/routines.linalg.html


| Funções | Descrição |
| :-- | :-- |
| linalg.eig(A) | retorna os autovalores e autovetores da matrix **A** |


In [76]:
import sympy as sp

lamb = sp.symbols("lambda")
A_s = sp.Matrix([[5.0, 3, -1], [3, 4, 0], [-1, 0, 2]])
A_s

Matrix([
[5.0, 3, -1],
[  3, 4,  0],
[ -1, 0,  2]])

In [77]:
ide = sp.eye(3) * lamb
ide

Matrix([
[lambda,      0,      0],
[     0, lambda,      0],
[     0,      0, lambda]])

In [78]:
eq = A_s - ide
eq

Matrix([
[5.0 - lambda,          3,         -1],
[           3, 4 - lambda,          0],
[          -1,          0, 2 - lambda]])

In [79]:
eq2 = eq.det()
eq2

-lambda**3 + 11.0*lambda**2 - 28.0*lambda + 18.0

In [80]:
sp.solve(eq2, lamb)

[1.00000000000000, 2.35424868893541, 7.64575131106459]

In [89]:
# Com o numpy
import numpy as np

A = np.array([[5.0, 3, -1], [3, 4, 0], [-1, 0, 2]])

In [82]:
np.linalg.eig(A)

(array([7.64575131, 1.        , 2.35424869]),
 array([[-0.76505532, -0.57735027, -0.28523152],
        [-0.6295454 ,  0.57735027,  0.51994159],
        [ 0.13550992, -0.57735027,  0.8051731 ]]))

In [83]:
l, v = np.linalg.eig(A)

In [84]:
l

array([7.64575131, 1.        , 2.35424869])

In [85]:
v

array([[-0.76505532, -0.57735027, -0.28523152],
       [-0.6295454 ,  0.57735027,  0.51994159],
       [ 0.13550992, -0.57735027,  0.8051731 ]])

## 8.9. Solver para Sistemas lineares

- https://numpy.org/doc/stable/reference/routines.linalg.html


| Função | Descrição |
| :-- | :-- |
| .linalg.solve(A, B) | resolve um sistema do tipo AX= B |

## 7.10. Exercício 5
Dadas as matrizes, resolva o sistema de equação $[A].\{X\} = \{B\}$

$$ A=
 \begin{bmatrix}
   1 & 1 & 1 \\\\
   1 & 2 & 2 \\\\
   2 & 1 & 3 
\end{bmatrix}
$$

$$ X=
 \begin{bmatrix}
   x_1 \\\\
   x_2 \\\\
   x_3 
\end{bmatrix}
$$

$$ B=
 \begin{bmatrix}
   6 \\\\
   9 \\\\
   11 
\end{bmatrix}
$$

In [86]:
import numpy as np

A = np.array(
    [
        [
            1,
            1,
            1,
        ],
        [1, 2, 2],
        [2, 1, 3],
    ]
)

A

array([[1, 1, 1],
       [1, 2, 2],
       [2, 1, 3]])

In [87]:
B = np.array([6, 9, 11])
B.ndim

1

In [88]:
np.linalg.solve(A, B)

array([3., 2., 1.])