# 11. Scipy

https://docs.scipy.org/doc/scipy/reference/

O scipy não é tratado como uma biblioteca, mas como um software composto por várias bibliotecas

# 11.1. Álgebra linear (linalg)


## 11.1.1. Funções para álgebra linear

**from scipy import linalg**

#### Propriedades de arrays


| Funções | Descrição |
| :-- | :-- |
| linalg.inv(arg) | Retona a inversa de uma matriz  |
| linalg.det(arg) | Acha a determinante de uma matriz  |
| linalg.norm(arg) | Acha a norma de um vetor |
| linalg.solve(arg) | Resolve um sistema linear  (mais eficiente que o sympy)|
|  linalg.eig(arg) | Retorna autovalor e autovetor |


In [1]:
from scipy import linalg
import numpy as np


In [2]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
A[0,0] = 10
A

array([[10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [4]:
A[0][0] = 7
A

array([[7, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
linalg.det(A)

-21.00000000000004

In [6]:
linalg.inv(A)

array([[ 0.14285714, -0.28571429,  0.14285714],
       [-0.28571429, -2.0952381 ,  1.38095238],
       [ 0.14285714,  2.04761905, -1.19047619]])

## 11.1.2. Exercício 1
Dadas as matrizes A,B, C e D, calcule, para cada uma, o determinante, a matriz transposta e a matriz inversa.

$$ A=
 \begin{bmatrix}
   1 & 2 \\\\
   4 & 5
  \end{bmatrix}
$$

$$ B=
 \begin{bmatrix}
   cos(\pi/4) & -sen(\pi/4) \\\\
   sen(\pi/4) & cos(\pi/4)
  \end{bmatrix}
$$

$$ C=
 \begin{bmatrix}
   2 & -2 \\\\
   -2 & 5
  \end{bmatrix}
$$

$$
D=
 \begin{bmatrix}
   2 & 2 \\\\
   4 & 4
  \end{bmatrix}
$$


Notas:
- A tem determinante diferente de zero
- B é uma matriz ortogonal, sua inversa é igual a sua transposta, e seu det deve ser + ou -1
- C é uma matriz simétrica, ela é igual a sua transposta
- D possui determinante igual a zero, portanto não é inversível

In [7]:
A = np.array([[1,2],[4,5]])
B = np.array([[np.cos(np.pi/4), -np.sin(np.pi/4)],
            [np.sin(np.pi/4), np.cos(np.pi/4)]])
C = np.array([[2,-2],[-2,5]])
D = np.array([[2,2],[4,4]])


In [8]:
linalg.det(A)

-3.0

In [9]:
A.T

array([[1, 4],
       [2, 5]])

In [10]:
linalg.inv(A)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [11]:
linalg.det(B)
B.T

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [12]:
linalg.inv(B)

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [13]:
C.T

array([[ 2, -2],
       [-2,  5]])

In [14]:
linalg.det(D)

0.0

## 11.1.3. Exercício 2
Dadas as matrizes, resolva o sistema de equação $[A].\{X\} = \{B\}$

$$ A=
 \begin{bmatrix}
   1 & 1 & 1 \\\\
   1 & 2 & 2 \\\\
   2 & 1 & 3 
\end{bmatrix}
$$

$$ X=
 \begin{bmatrix}
   x_1 \\\\
   x_2 \\\\
   x_3 
\end{bmatrix}
$$

$$ B=
 \begin{bmatrix}
   6 \\\\
   9 \\\\
   11 
\end{bmatrix}
$$

In [15]:
A = np.array([[1,1,1],[1,2,2],[2,1,3]])
B = np.array([6,9,11])
B

array([ 6,  9, 11])

In [16]:
x = linalg.solve(A, B)
x

array([3., 2., 1.])

In [17]:
A@x

array([ 6.,  9., 11.])

## 11.1.4. Exercício 3
Ache os autovalores e autovetores para as matrizes abaixo.

$$ A=
 \begin{bmatrix}
   -1 & 6 \\\\
   0 & 5
  \end{bmatrix}
$$

$$ B=
 \begin{bmatrix}
   -1/3 & 0 & 0 \\\\
   0 & 1 & 0 \\\\
   0 & 0 & 1/2
  \end{bmatrix}
$$

O autovalor e autovetor se associam à matriz da seguinte forma:

$$ [A] \{X\} = \lambda \{X\} $$

In [18]:
A = np.array([[-1, 6],[0, 5]])
B = np.array([[-1/3, 0, 0],[0, 1, 0],[0, 0, 0.5]])

In [19]:
autovalor, autovetor = linalg.eig(A)
# Primeira linha autovalores
# Segunda linha autovetores na coluna.


In [20]:
type(autovetor)

numpy.ndarray

In [21]:
autovetor[::, 0]

array([1., 0.])

# 11.2 - Cálculo (integrate)
## 11.2.1 - Integral
**from scipy.integrate import quad, dblquad**


| Funções | Descrição |
| :-- | :-- |
| integrate.quad(func, a, b) | Calcula a integral de uma função  |
| integrate.dbquad(func, a, b, gfun, hfun) | Calcula a integral dupla de uma função  |

https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.quad.html#scipy.integrate.quad

https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.dblquad.html#scipy.integrate.dblquad


In [22]:
import numpy as np
from scipy.integrate import quad, dblquad

In [23]:
# x**2

f_x = lambda x: x**2

In [24]:
quad(f_x, 0,10)

(333.33333333333326, 3.700743415417188e-12)

In [25]:
#check
I_x = lambda x: x**3/3
I_x(10)

333.3333333333333

In [26]:
# x**2 + y

f_xy = lambda x,y: x*y

In [27]:
dblquad(f_xy, 0,5, lambda y:0, lambda y:10)

(624.9999999999999, 6.938893903907227e-12)

In [28]:
I_xy = lambda x,y: (x**2/2)*( y**2/2)
I_xy(5,10)

625.0

## 11.2.2 Exercício 1

Dadas as funções, calcule sua integral com  x variando de 0 a 10: 
$$ A(x) = e^x $$

$$ B(x) = x^3 $$

$$ C(x) = 1/x $$

In [29]:
a_x = lambda x: np.exp(x)
quad(a_x, 0, 10)

(22025.465794806725, 6.239389118119928e-10)

In [30]:
# check
np.exp(10) - np.exp(0)

22025.465794806718

In [31]:
b_x = lambda x: x**3
quad(b_x, 0, 10)

(2500.0000000000005, 2.775557561562892e-11)

In [32]:
10**4/4

2500.0

In [33]:
c_x = lambda x: 1/x
quad(c_x, 1, 10)

(2.302585092994052, 1.7485989740926124e-08)

In [34]:
np.log(10)-np.log(1)

2.302585092994046

## 11.2.3 Exercício 2
Calcule a integral dupla:
$$ A(x,y) = \iint_{A}dx.dy   $$

Considere: $ 0 \le x \le 3 $ e $ 0 \le y \le 4 $

In [35]:
a_xy = lambda x,y: 1

In [36]:
dblquad(a_xy, 0, 3, lambda y:0, lambda y:4)

(12.0, 1.3322676295501878e-13)

## 11.2.4 - EDO
**from scipy.integrate import odeint**


| Funções | Descrição |
| :-- | :-- |
| integrate.odeint(func, y0, t) | Calcula a dada equação diferencial  |



https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html#scipy.integrate.odeint

In [37]:
import sympy as sp
x = sp.symbols('x')

y_x = sp.Function('y_x')
dy_x = sp.Derivative(y_x(x), x)
eq = dy_x + 10*x

sp.dsolve(eq)

Eq(y_x(x), C1 - 5*x**2)

In [38]:
from scipy.integrate import odeint

In [39]:
def eq_dif(u, x):
    y,dy = u
    func = [dy, -10*x]
    return func



In [40]:
x = list(range(11))

odeint(eq_dif, [0,0,], x)

array([[    0.        ,     0.        ],
       [   -1.66666669,    -5.00000002],
       [  -13.33333337,   -20.00000002],
       [  -45.00000006,   -45.00000002],
       [ -106.66666675,   -80.00000002],
       [ -208.33333344,  -125.00000002],
       [ -360.00000012,  -180.00000002],
       [ -571.66666681,  -245.00000002],
       [ -853.3333335 ,  -320.00000002],
       [-1215.00000019,  -405.00000002],
       [-1666.66666687,  -500.00000002]])

## 11.2.4 - Desafio 1 (técnicas para resolver EDO de segunda ordem)


Resolver a EDO a seguir utilizando o Scipy.


$$ \ \ m\ddot{x}(t) + c\dot{x}(t) + kx(t)=0; \ \ com\ x(0) = x_0 \ e\  \dot{x}(0) = v_0   $$

Para fazer a comparação, iremos adotar os valores:
$$ \ \ 10\ddot{x}(t) + 20\dot{x}(t) + 50x(t)=0; \ \ com\ x(0) = 10 \ e\  \dot{x}(0) = 0   $$